cache:
  directories:
  - $HOME/.m2

language: java

services:
  - redis-server
  - mongodb

jdk:
  - oraclejdk8


after_script:
  - "./.utility/.coverage.sh"

notifications:
  email:
    recipients:
    - gastonprietoutn@gmail.com
    - mtisot@gmail.com
    - leilaweic@hotmail.com
    - ailenmunozz@gmail.com
    - michu.rabinovich@hotmail.com
    - berco.fede@gmail.com

env:
  global:
    secure: e11Lo035ZIv6LQzBGpiokyrPMgcSjQ8JIKvi2YzNTjC5jnGZbZUmi4BDdS69Rx4ohVce5HpSecR1MrIfCkFbpz6Iml1tuWBRDOR1/K2i6EW8veW6KlgnYnqI9t6lGbsHI/odNEsWaYNkeg3zMAww4FdFfVfdI+mlFMZq2OThpXwLk6Mxzwsib7ptxdj1VGBvykJm0JifQWqqe+5p1NpLD6dmb/8CkbWOzhcPU3HfseYs9wdwN20J2CgCJHKf8ywKo/QztCx+rJ+T2hf7Jtb7zFWB/8d+3oP00s1AUuWDZ2ZyvDQe9aGZFsC2WmecQggSUwROVeq9dmDvhSxdh55TE9dayVPsbjWxHyuWuxjFhbp78rnlGc4wk4tTTVGXdxbU1z/9Z/a7wx4xCVAO6LrWl9gkofav+rN97/o5ktImdtn2zQlCclqYctagR4FcWjAFm9OlZzBAhkx8VnuM/gk2plI/OI9zbH1gGIhsIwy+hgYNMF4nV1AkNpyPmTHuWNVkKVITQt51N2FNdPorKFNQwc7mHJaxIx/z/IdNjx1qxMvt24yuJEOL4WQqkIWqsssh3sv4wBa22rwqrEZStG8vAQ1e0Al0aWieN4+nDaiH/QnZOJ/sPF3mQ3nC8SGBTnG3N2GVfvaOaVOMVySo3L3ETWUlE3WiwPz5G/rsOKU2zJQ=
